[theme]
primaryColor = "#FF4B4B"           # Bright red for buttons, sliders, highlights
backgroundColor = "#121212"        # Dark background
secondaryBackgroundColor = "#1E1E1E" # Sidebar background
textColor = "#FFFFFF"              # White text for contrast
font = "sans serif"                # Clean font
